import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';
import Header from '@/components/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
	team,
	dashboard,
}: {
	children: ReactNode;
	team: ReactNode;
	dashboard: ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main className="container">
					<Header />
					<section className="py-6">{children}</section>
					<section className="flex gap-6">
						{team}
						{dashboard}
					</section>
				</main>
			</body>
		</html>
	);
}
